//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.12 at 05:49:36 PM NZST 
//


package com.jcasey.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jcasey.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jcasey.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Books }
     * 
     */
    public Books createBooks() {
        return new Books();
    }

    /**
     * Create an instance of {@link Books.Book }
     * 
     */
    public Books.Book createBooksBook() {
        return new Books.Book();
    }

    /**
     * Create an instance of {@link Books.Book.Genres }
     * 
     */
    public Books.Book.Genres createBooksBookGenres() {
        return new Books.Book.Genres();
    }

    /**
     * Create an instance of {@link Books.Book.Genres.Genre }
     * 
     */
    public Books.Book.Genres.Genre createBooksBookGenresGenre() {
        return new Books.Book.Genres.Genre();
    }

}
